### ISSUE TITLE
Missing exclamation point

### ISSUE THREAD

**Issue by chrissexton** [KylePDavis/kylepdavis.github.com#1]
The text "Hello World" is missing the exclamation point at the end.

**Comment by KylePDavis** [comment]
Fixed. Moved it to right hand column as a title attribute of the image element in commit [1bb6239:/_includes/right.html#L4](https://github.com/KylePDavis/kylepdavis.github.com/blob/1bb623973353754865b1a48cb09c1bcaa101b34b/_includes/right.html#L4).
Thanks! ;-)
